version: "3.8"
services:
  councilor-front:
    image: miari/councilor-front
    ports:
      - 80:80

  councilor-back:
    depends_on:
      councilor-db:
        condition: service_healthy

    image: miari/councilor-back
    ports:
      - 8080:1323

  councilor-db:
    image: mysql:8.0-debian
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: webapp
      # MYSQL_USER: root
      # MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    healthcheck:
      test: "mysqladmin ping -h 127.0.0.1"
      timeout: 20s
      retries: 10
      interval: 2s

    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./conf/mysql:/etc/mysql/conf.d
      - my-vol:/var/lib/mysql
volumes:
  my-vol:
